#!/usr/bin/ksh
cd sybase
rm ../reports/sp_sysmon.by_device.*

#
# For each sb_sysmon file, rotate the device entries to a comma delimited line on time.
echo "Reading ODS sb_sysmon data..."
for file in ODS*
do
	echo "   $file"
	gawk '{
		if( FILENAME != filename ) {
			filename = FILENAME ;
			reads = 0 ; writes = 0 ; 
			fcnt = fcnt + 1 ; lcnt = 0 ; flag = 0 ;
			split( FILENAME, tary, "." ) ;
			split( tary[2], ttary, "_" ) ;
			date = sprintf("%s/%s",substr(ttary[1],5,2),substr(ttary[1],7,2)) ;
			time = sprintf("%s:%s",substr(ttary[2],1,2),substr(ttary[2],3,2)) ;
			rc = 0 ; rp = 0 ; rs = 0 ; rx = 0 ;
			wc = 0 ; wp = 0 ; ws = 0 ; wx = 0 ;
			tc = 0 ; ts = 0 ; tx = 0 ;
			swc = 0 ; swp = 0 ; sws = 0 ; swx = 0 ;
			SGC = 0 ; SGP = 0 ; SGS = 0 ; SGX = 0 ;
			}	
		if( $1 == "Device:" ) {
			getline ; split($1,tary,"/"); vg = tary[3] ; lv = substr(tary[4],2) ;
			outfile = sprintf("../reports/sp_sysmon.by_device.%s.%s.cdl",vg,lv) ;
			flag = 1 ;
			}
		if( flag == 1 && $1 == "APF" ) {
			rc = $4 ; rp = $5 ; rs = $2 ; rx = $3 ; getline ;
			rc = rc + $4 ; rp = rp + $5 ; rs = rs + $2 ; rx = rx + $3 ; 	
			}
		if( flag == 1 && $1 == "Writes" ) {
			wc = $4 ;  wp = $5 ; ws = $2 ; wx = $3 ;
			}
		if( flag == 1 && $1 == "Total" ) { 
			tc = $5 ; ts = $3 ; tx = $4 ;
			}	
		if( flag == 1 && $3 == "Granted" ) {
			SGC = $6 ; SGS = $4 ; SGX = $5 ; SGP = $7 ; getline ;
			swc = $6 ; sws = $4 ; swx = $5 ; swp = $7 ;
			}
		if( flag == 1 && $1 == "-----------------------------------------------------------------------------" ) {
			printf "%s %s,",date,time >> outfile ;
			printf "%s,%s,%s,%s,",rc,rs,rx,rp >> outfile ;
			printf "%s,%s,%s,%s,",wc,ws,wx,wp >> outfile ;
			printf "%s,%s,%s,",tc,ts,tx >> outfile ;
			printf "%s,%s,%s,%s,",SGC,SGS,SGX,SGP >> outfile ;
			printf "%s,%s,%s,%s\n",swc,sws,swx,swp >> outfile ;
			close( outfile ) ; 
			flag = 0 ;
			rc = 0 ; rp = 0 ; rs = 0 ; rx = 0 ;
			wc = 0 ; wp = 0 ; ws = 0 ; wx = 0 ;
			tc = 0 ; ts = 0 ; tx = 0 ;
			swc = 0 ; swp = 0 ; sws = 0 ; swx = 0 ;
			SGC = 0 ; SGP = 0 ; SGS = 0 ; SGX = 0 ;
			}
		}' $file
done
cd ../reports
for file in sp_sysmon.by_device*
do
	echo "Date,Reads,sec,xact,%,Writes,sec,xact,%,Total,sec,xact,SemaGet,sec,xact,%,SemaWait,sec,xact,%" > /tmp/get_devices.tmp
	cat $file >> /tmp/get_devices.tmp
	cp /tmp/get_devices.tmp $file
done
	
exit
#
# Get the time stamps for the files for filling in gaps in data
echo "Fixing date stamps..."
ls -rt ODS* > ../reports/ods.ts
cd ../reports
for file in sp_sysmon.by_device*
do
	echo "   $file"
	gawk -F"," 'BEGIN {
			print "      reading datestamps."
			while( getline tstr  < "ods.ts" > 0 ) {
				tcnt = tcnt + 1 ;
				split(tstr,tary,".") ;	 
				split( tary[2], ttary, "_" ) ;
				d[tcnt] = sprintf("%s/%s",substr(ttary[1],5,2),substr(ttary[1],7,2)) ;
				t[tcnt] = sprintf("%s:%s",substr(ttary[2],1,2),substr(ttary[2],3,2)) ;
				} 
			print "         done"
			}
		{
			DS[$1] = $0 ;
			}
		END {
			print "      rolling it out again."
			print "Date,Reads,sec,xact,%,Writes,sec,xact,%,Total,sec,xact,SemaGet,sec,xact,%,SemaWait,sec,xact,%" > "temp" ;
			for( i=1; i<=tcnt; i++ ) {
				ds = sprintf("%s %s",d[i],t[i]) ;
				if( DS[ds] == "" ) {
					printf "%s %s\n",d[i],t[i] >> "temp" ;
					}
				else {
					print DS[ds] >> "temp" ;
					}
				}
			print "         done"
			}' $file 
	mv temp $file
done
				
		
